f=open("satish.txt")
# content=f.read()
# print(content)
# f.close()
# print(f.readlines())
print(f.readline(3))
# print(f.re
# print(f.readline())adline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
f.close()