# f=open("satish.txt")
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
# # print(f.readlines())
# f.close()
with open("satish.txt") as f:
    a=f.read()
    print(a)
print(f.__doc__)